blueprint:
  name: IKEA Tradfri On/Off Switch (E1743)
  description: Zet een lamp aan of uit met de IKEA Tradfri On/Off Switch (E1743).
  domain: automation
  input:
    tradfri_switch:
      name: "IKEA Tradfri On/Off Switch"
      description: "De IKEA Tradfri On/Off schakelaar"
      selector:
        entity:
          domain: mqtt
          device_class: "switch"
    light_entity:
      name: "Lamp"
      description: "De lamp die je wilt aansteken of uitzetten"
      selector:
        entity:
          domain: light

trigger:
  - platform: mqtt
    topic: !input tradfri_switch
    payload: "on"
  - platform: mqtt
    topic: !input tradfri_switch
    payload: "off"

action:
  - choose:
      - conditions:
          - condition: trigger
            id: on_trigger
        sequence:
          - service: light.turn_on
            target:
              entity_id: !input light_entity
      - conditions:
          - condition: trigger
            id: off_trigger
        sequence:
          - service: light.turn_off
            target:
              entity_id: !input light_entity
