blueprint:
  name: IKEA Tradfri Dimmer - Dim Licht
  description: Gebruik de IKEA Tradfri 2-button dimmer om de helderheid van een lamp te dimmen.
  domain: automation
  input:
    dimmer_button_1:
      name: "Knop 1"
      description: "Knop 1 (om op te stijgen)"
      selector:
        entity:
          domain: mqtt
          device_class: "button"
    dimmer_button_2:
      name: "Knop 2"
      description: "Knop 2 (om af te dalen)"
      selector:
        entity:
          domain: mqtt
          device_class: "button"
    light_entity:
      name: "Lamp"
      description: "De lamp die je wilt dimmen"
      selector:
        entity:
          domain: light

trigger:
  - platform: mqtt
    topic: !input dimmer_button_1
  - platform: mqtt
    topic: !input dimmer_button_2

action:
  - choose:
      - conditions:
          - condition: trigger
            id: dimmer_button_1
        sequence:
          - service: light.turn_on
            target:
              entity_id: !input light_entity
            data:
              brightness: "{{ state_attr('light.' ~ state('input_entity'), 'brightness') | default(0) + 25 }}"
      - conditions:
          - condition: trigger
            id: dimmer_button_2
        sequence:
          - service: light.turn_on
            target:
              entity_id: !input light_entity
            data:
              brightness: "{{ state_attr('light.' ~ state('input_entity'), 'brightness') | default(255) - 25 }}"
