automation:
  - alias: "Turn on light with Tradfri On/Off Switch"
    trigger:
      platform: mqtt
      topic: "zigbee2mqtt/your_switch/state"
      payload: "on"
    action:
      service: light.turn_on
      target:
        entity_id: light.your_light_entity

  - alias: "Turn off light with Tradfri On/Off Switch"
    trigger:
      platform: mqtt
      topic: "zigbee2mqtt/your_switch/state"
      payload: "off"
    action:
      service: light.turn_off
      target:
        entity_id: light.your_light_entity
